[project]
name = "appgrandeseventos"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "google-auth>=2.53.0",
    "gspread>=6.2.1",
    "itsdangerous>=2.1.0",
    "pandas>=3.0.3",
    "timezonefinder>=8.2.4",
]

[project.scripts]
app = "main:start"
