[project]
name = "appgrandeseventos"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "itsdangerous>=2.1.0",
    "pandas>=3.0.3",
    "timezonefinder>=8.2.4",
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.1",
]

[project.scripts]
app = "main:start"
