CREATE SCHEMA IF NOT EXISTS guia_programacao;
CREATE TABLE IF NOT EXISTS guia_programacao.tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL,
    titulo TEXT NOT NULL CHECK (char_length(titulo) BETWEEN 3 AND 100),
    descricao TEXT NOT NULL DEFAULT '' CHECK (char_length(descricao) <= 2000),
    status TEXT NOT NULL CHECK (status IN ('pendente', 'concluida')),
    prioridade TEXT NOT NULL CHECK (prioridade IN ('baixa', 'normal', 'alta')),
    fiscal_id BIGINT NOT NULL CHECK (fiscal_id IN (1, 2)),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_guia_tarefas_evento
    ON guia_programacao.tarefas(evento_id);
